CREATE DATABASE HorseRacing

go

Use HorseRacing

go

CREATE TABLE Races (
race_id INT PRIMARY KEY IDENTITY,
race_date DATETIME NOT NULL,
venue VARCHAR(2) NOT NULL,
race_no INT NOT NULL,
config VARCHAR(8) NOT NULL,
surface INT NOT NULL DEFAULT 0,
distance DECIMAL(5,2),
going VARCHAR(128),
horse_ratings VARCHAR(16),
prize DECIMAL(16,2),
race_class INT,
sec_time1 DECIMAL(5,2),
sec_time2 DECIMAL(5,2),
sec_time3 DECIMAL(5,2),
sec_time4 DECIMAL(5,2),
sec_time5 DECIMAL(5,2),
sec_time6 DECIMAL(5,2),
sec_time7 DECIMAL(5,2),
time1 DECIMAL(5,2),
time2 DECIMAL(5,2),
time3 DECIMAL(5,2),
time4 DECIMAL(5,2),
time5 DECIMAL(5,2),
time6 DECIMAL(5,2),
time7 DECIMAL(5,2),
place_combination1 INT,
place_combination2 INT,
place_combination3 DECIMAL(5,2),
place_combination4 DECIMAL(5,2),
place_divident1 DECIMAL(5,2),
place_divident2 DECIMAL(5,2),
place_divident3 DECIMAL(5,2),
place_divident4 DECIMAL(5,2),
win_combination1 INT,
win_divident1 DECIMAL(5,2),
win_combination2 INT,
win_divident2 DECIMAL(5,2),
);

CREATE TABLE Runs (
race_id INT PRIMARY KEY IDENTITY,
horse_no INT,
horse_id INT,
result DECIMAL(5,2),
won DECIMAL(2,2),
lengths_behind DECIMAL(5,2),
horse_age INT,
horse_country VARCHAR(8),
horse_type VARCHAR(32),
horse_rating INT,
horse_gear VARCHAR(32),
declared_weight DECIMAL(5,2),
actual_weight DECIMAL(5,2),
draw INT,
position_sec1 DECIMAL(4,2),
position_sec2 DECIMAL(4,2),
position_sec3 DECIMAL(4,2),
position_sec4 DECIMAL(4,2),
position_sec5 DECIMAL(4,2),
position_sec6 DECIMAL(4,2),
behind_sec1 DECIMAL(4,2),
behind_sec2 DECIMAL(4,2),
behind_sec3 DECIMAL(4,2),
behind_sec4 DECIMAL(4,2),
behind_sec5 DECIMAL(4,2),
behind_sec6 DECIMAL(4,2),
time1 DECIMAL(5,2),
time2 DECIMAL(5,2),
time3 DECIMAL(5,2),
time4 DECIMAL(5,2),
time5 DECIMAL(5,2),
time6 DECIMAL(5,2),
finish_time DECIMAL(5,2),
win_odds DECIMAL(4,2),
place_odds DECIMAL(4,2),
trainer_id INT,
jockey_id INT
);