Create DATABASE HorseRacingWH

go 

USE HorseRacingWH

go

CREATE TABLE Jockeys(
	ID INT PRIMARY KEY IDENTITY,
	Country VARCHAR(255),
);

CREATE TABLE Trainers(
	ID INT PRIMARY KEY IDENTITY,
	Country VARCHAR(255),
);

CREATE TABLE Races(
	ID INT PRIMARY KEY IDENTITY,
	RaceDate DATETIME NOT NULL,
	Venue VARCHAR(255) NOT NULL,
	Surface INT NOT NULL DEFAULT 0,
	Distance int,
	HorseRatings VARCHAR(255),
	Prize VARCHAR(255)
);

CREATE TABLE Horses(
	ID INT PRIMARY KEY IDENTITY,
	Age INT,
	Country VARCHAR(255),
	HorseType VARCHAR(255),
	Rating VARCHAR(255),
	DeclaredlWeight VARCHAR(255)
);

CREATE TABLE Runs(
	ID INT PRIMARY KEY IDENTITY,
	RaceID INT NOT NULL,
	HorseID INT NOT NULL,
	TrainerID INT NOT NULL,
	JockeyID INT NOT NULL,
	Result INT,
	ActualWeight VARCHAR(255),
	PositionSec1 VARCHAR(255),
	PositionSec2 VARCHAR(255),
	PositionSec3 VARCHAR(255),
	PositionSec4 VARCHAR(255),
	PositionSec5 VARCHAR(255),
	PositionSec6 VARCHAR(255),
	BehindSec1 VARCHAR(255),
	BehindSec2 VARCHAR(255),
	BehindSec3 VARCHAR(255),
	BehindSec4 VARCHAR(255),
	BehindSec5 VARCHAR(255),
	BehindSec6 VARCHAR(255),
	Time1 VARCHAR(255),
	Time2 VARCHAR(255),
	Time3 VARCHAR(255),
	Time4 VARCHAR(255),
	Time5 VARCHAR(255),
	Time6 VARCHAR(255),
	FinishTime VARCHAR(255),
	FOREIGN KEY (RaceID) REFERENCES Races(ID),
	FOREIGN KEY (HorseID) REFERENCES Horses(ID),
	FOREIGN KEY (TrainerID) REFERENCES Trainers(ID),
	FOREIGN KEY (JockeyID) REFERENCES Jockeys(ID)
);